DATA:
  grasp_size_factor: 300
  grasp_height: 20.0
  grasp_size_coordinate: canvas
  dataset: vcot
  root_path: ./datasets/graspanything-vcot
  split_root: ./datasets/graspanything-vcot/split/vcot
  prompt_template: "Grasp the {object_name}"
  train_split: train_official
  val_split: val_official
  grasp_target_policy: all
  vcot_official_val_size: 5000
  offset_r: 20
  offset_sigma:
MODEL:
  architecture: ggcnnclip
TRAIN:
  clip_pretrain: pretrain/RN50.pt
  version: multiple
  input_channels: 3
  input_size: 416
  word_len: 17
  word_dim: 1024

  sync_bn: False
  amp: False
  optimizer: adam
  pin_memory: False
  workers: 8  # per process; 16 workers total with two NPUs
  workers_val: 4
  epochs: 50
  milestones: [35]
  start_epoch: 0
  batch_size: 64  # global batch size
  batch_size_val: 64  # global validation batch size
  base_lr: 0.00001
  lr_decay: 0.1
  lr_multi: 0.1
  weight_decay: 0.0
  max_norm: 1.0
  manual_seed: 0
  print_freq: 50
  exp_name: ggcnnclip_vcot
  predict_grasp_short_side: True
  short_side_loss_weight: 1.0
  output_folder: exp/vcot
  save_freq: 20
  weight:
  resume:
  evaluate: True
  use_pretrained_clip: True
  use_grasp_masks: True
Distributed:
  dist_url: env://
  dist_backend: hccl
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
TEST:
  grasp_size_activation: auto
  test_split: unseen
  evaluation_protocol: vcot_official
  grasp_topk: [1]
  grasp_iou_threshold: 0.25
  grasp_angle_threshold: 30.0
  filter_grasps_by_segmentation: False
  restore_grasp_size_scale: True
  visualize: False



