DATA:
  dataset: OCID-VLG
  root_path: ./datasets/OCID-VLG
  with_depth: False
  train_split: train
  val_split: val
  offset_r: 20
  offset_sigma:
MODEL:
  architecture: maplegrasp
TRAIN:
  version: multiple
  clip_pretrain: pretrain/RN50.pt
  input_size: 416
  word_len: 17
  word_dim: 1024
  vis_dim: 512
  fpn_in: [512, 1024, 1024]
  fpn_out: [256, 512, 1024]
  sync_bn: True
  amp: False
  optimizer: adam
  pin_memory: False
  num_layers: 3
  num_head: 8
  dim_ffn: 2048
  dropout: 0.1
  intermediate: False
  use_contrastive: True
  use_pretrained_clip: True
  use_grasp_masks: True
  maple_stage: joint
  maple_mask_threshold: 0.35
  maple_hard_mask: True
  maple_use_gt_masks: False
  maple_grasp_loss_weight: 1.0
  workers: 8
  workers_val: 4
  epochs: 50
  milestones: [35, 45]
  start_epoch: 0
  batch_size: 8
  batch_size_val: 8
  base_lr: 0.0001
  lr_decay: 0.1
  lr_multi: 0.1
  weight_decay: 0.0
  max_norm: 0.0
  manual_seed: 0
  print_freq: 100
  exp_name: maplegrasp_ocid_vlg
  output_folder: exp/ocid_vlg
  save_freq: 5
  weight:
  resume:
  evaluate: True
Distributed:
  dist_url: env://
  dist_backend: hccl
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
TEST:
  test_split: test
  visualize: False
